dev_authorized_key: "ssh-ed25519 REPLACE_ME"

server_timezone: Europe/Moscow
swapfile_path: /swapfile
swapfile_size_mb: 2048

root_domain: example.com

authelia_username: dev
authelia_display_name: Dev User
authelia_dir: /opt/authelia

base_packages:
  - git
  - curl
  - tmux
  - ufw
  - ca-certificates
